services:

  response_cache_bundle_reflection_scanner:
    class: Pada\Reflection\Scanner\Scanner
    arguments: [ '@annotations.reader' ]

  response_cache_bundle_expression_service:
    class: Pada\ResponseCacheBundle\Service\ExpressionService
    arguments: ['@cache.system']

  response_cache_bundle_key_generator_service:
    class: Pada\ResponseCacheBundle\Service\KeyGenerator
    arguments: ['@response_cache_bundle_expression_service']

  # ---
  # Cacheable Service
  response_cache_bundle_cacheable_service:
    class: Pada\ResponseCacheBundle\Service\CacheableService
    arguments: [
        '@response_cache_bundle_reflection_scanner',
        '@service_container',
        '@cache.system',
        '@response_cache_bundle_expression_service',
        '@response_cache_bundle_key_generator_service',
        null
    ]

  # ---
  # Evict Service
  response_cache_bundle_evict_service:
    class: Pada\ResponseCacheBundle\Service\EvictService
    arguments: [
        '@response_cache_bundle_reflection_scanner',
        '@service_container',
        '@cache.system',
        '@response_cache_bundle_key_generator_service'
    ]

  # ---
  # Cache Warmer
  response_cache_bundle_cache_warmer:
    public: true
    class: Pada\ResponseCacheBundle\Cache\CacheWarmer
    arguments: [
        '%kernel.project_dir%/src',
        '@response_cache_bundle_cacheable_service',
        '@response_cache_bundle_evict_service'
    ]
    tags:
      - { name: kernel.cache_warmer, priority: 0 }

  # ---
  # Event listeners
  Pada\ResponseCacheBundle\EventListener\ControllerListener:
    arguments: ['@response_cache_bundle_cacheable_service', '@response_cache_bundle_evict_service']
    tags:
      - { name: kernel.event_listener, event: kernel.controller, priority: 1500 }

  Pada\ResponseCacheBundle\EventListener\ResponseListener:
    arguments: ['@response_cache_bundle_cacheable_service']
    tags:
      - { name: kernel.event_listener, event: kernel.response, priority: 1500 }

  Pada\ResponseCacheBundle\EventListener\ExceptionListener:
    arguments: ['@response_cache_bundle_cacheable_service']
    tags:
      - { name: kernel.event_listener, event: kernel.exception }
